---
# Requires proj_name set at runtime
- name: Run localhost roles
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: pull

    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: addchange

    - name: Import inmem_inv role
      ansible.builtin.include_role:
        name: eingram23.homelab.inmem_inv

    - name: Import terraform_apply role
      ansible.builtin.include_role:
        name: eingram23.tf_build.terraform
        tasks_from: apply

- name: Deploy new server(s) - run roles against piholes
  hosts: piholes
  gather_facts: false
  become: true
  become_method: sudo
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: update

    - name: Pause 20 seconds for pihole update
      ansible.builtin.pause:
        seconds: 20

- name: Run localhost roles
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: Push custom.list to git and clean up
      ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: push

    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: cleanup

- name: Run post build tasks against new server(s)
  hosts: temp_group
  become: true
  become_method: sudo

  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.homelab.rhel_sub
        tasks_from: add
      when: ansible_facts['distribution'] == 'RedHat'

    - ansible.builtin.include_role:
        name: eingram23.homelab.add_eingram_user

    - ansible.builtin.include_role:
        name: eingram23.homelab.chrony

    - ansible.builtin.include_role:
        name: eingram23.homelab.install_core_pkgs

    - ansible.builtin.include_role:
        name: eingram23.homelab.container_host
      when: "'container_host' in task"

    - ansible.builtin.include_role:
        name: eingram23.splunk.splunk_uf
      when: "'splunk_uf' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.snmpd
      when: "'snmpd' in task"

    - ansible.builtin.include_role:
        name: eingram23.metrics.node_exporter
      when: "'node_exporter' in task"

- name: Add target to prometheus server
  hosts: dbsrv1.local.lan
  gather_facts: false
  become: true
  become_user: poduser
  become_method: sudo
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.metrics.prom_target_update
        tasks_from: add
      vars:
        prom_port: "9100"
      when: "'node_exporter' in task"

- name: Add host to LibreNMS
  hosts: librenms.local.lan
  gather_facts: false
  become: true
  become_user: librenms
  become_method: sudo
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.homelab.snmpd
        tasks_from: add
      when: "'snmpd' in task"
