---
# Requires proj_name set at runtime
- name: Deploy Terraform plan
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  tasks:

    - block:
        - ansible.builtin.include_role:
            name: eingram23.pihole.localdns
            tasks_from: pull

        - ansible.builtin.include_role:
            name: eingram23.pihole.localdns
            tasks_from: addchange
      when: vm_folder_name == "WindowsWG"

    - ansible.builtin.include_role:
        name: eingram23.homelab.inmem_inv
      vars:
        inmem_user: "ansible"
      when: vm_folder_name == "WindowsWG"

    - ansible.builtin.include_role:
        name: eingram23.homelab.inmem_inv
      vars:
        inmem_user: "ansible@HOMELAB.LOCAL"
      when: vm_folder_name == "WindowsHL"

    - ansible.builtin.include_role:
        name: eingram23.tf_build.terraform
        tasks_from: apply

- name: Create DNS entries in Pihole
  hosts: piholes
  gather_facts: false
  become: true
  become_method: sudo
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  tasks:

    - block: 
        - ansible.builtin.include_role:
            name: eingram23.pihole.localdns
            tasks_from: update
        
        - name: Pause for 20 seconds for pihole update
          ansible.builtin.pause:
            seconds: 20
      when: vm_folder_name == "WindowsWG"

- name: Run localhost roles
  hosts: localhost
  gather_facts: false
  become: false

  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  tasks:

    - block:
        - name: Push custom.list to git and clean up
          ansible.builtin.include_role:
            name: eingram23.pihole.localdns
            tasks_from: push

        - ansible.builtin.include_role:
            name: eingram23.pihole.localdns
            tasks_from: cleanup
      when: vm_folder_name == "WindowsWG"
        
- name: Run post build tasks against new server(s)
  hosts: temp_group
  become: true
  become_method: runas

  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.homelab.snmpd
        tasks_from: win_snmp
      when: "'snmp' in task"

    - ansible.builtin.include_role:
        name: eingram23.metrics.windows_exporter
      when: "'windows_exporter' in task"

- name: Add target to prometheus server
  hosts: dbsrv1.local.lan
  gather_facts: false
  become: true
  become_user: poduser
  become_method: sudo

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.metrics.prom_target_update
        tasks_from: add
      vars:
        prom_port: "9182"
      when: "'windows_exporter' in task"

- name: Add host to LibreNMS
  hosts: librenms.local.lan
  gather_facts: false
  become_user: librenms
  become_method: sudo

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.homelab.snmpd
        tasks_from: add
      when: "'snmp' is in task"
