---
- name: Deploy Terraform plan
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  collections:
    - eingram23.homelab
    - eingram23.tf_build

  tasks:

    - ansible.builtin.include_role:
        name: inmem_inv

    - ansible.builtin.include_role:
        name: terraform
        tasks_from: apply

- name: Create DNS entries in Pihole
  hosts: piholes
  gather_facts: false
  become: true
  become_method: sudo
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml
  
  collections:
    - eingram23.pihole

  tasks:

    - ansible.builtin.include_role:
        name: update_localdns
        tasks_from: add
      when: vm_folder_name == "WindowsWG"
