---
# Requires proj_name set at runtime

- name: Deploy new server(s) - run roles against piholes
  hosts: piholes
  gather_facts: false
  become: true
  become_method: sudo
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  collections:
    - eingram23.pihole
  
  tasks:

    - import_role:
        name: update_localdns
        tasks_from: add

- name: Run localhost roles
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  collections:
    - eingram23.homelab
    - eingram23.tf_build
    - eingram23.splunk
    - eingram23.metrics

  tasks:

    - name: Import inmem_inv role
      import_role:
        name: inmem_inv

    - name: Import terraform_apply role
      import_role:
        name: terraform
        tasks_from: apply

- name: Run post build tasks against new server(s)
  hosts: temp_group
  become: true
  become_method: sudo

  collections:
    - eingram23.homelab
    - eingram23.splunk
    - eingram23.metrics

  tasks:

    - ansible.builtin.include_role:
        name: rhel_sub
        tasks_from: add
      when: ansible_facts['distribution'] == 'RedHat'
    - ansible.builtin.include_role: 
        name: add_eingram_user
    - ansible.builtin.include_role: 
        name: chrony
    - ansible.builtin.include_role:
        name: install_core_pkgs

    - ansible.builtin.include_role:
        name: container_host
      when: "'container_host' in tasks"
    - ansible.builtin.include_role:
        name: webapps
      when: "'webapps' in tasks"
    - ansible.builtin.include_role:
        name: splunk_uf
      when: "'splunk_uf' in tasks"
    - ansible.builtin.include_role:
        name: snmpd
      when: "'snmpd' in tasks"
    - ansible.builtin.include_role:
        name: node_exporter
      when: "'node_exporter' in tasks"

- name: Add target to prometheus server
  hosts: grafana.local.lan
  gather_facts: false
  become: true
  become_user: poduser
  become_method: sudo
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  collections:
    - eingram23.metrics
     
  tasks:
  
    - import_role:
        name: prom_target_update
        tasks_from: add
      when: "'node_exporter' in tasks"

- name: Add host to LibreNMS
  hosts: librenms.local.lan
  gather_facts: false
  become: true
  become_user: librenms
  become_method: sudo
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  collections:
    - eingram23.homelab

  tasks:

    - ansible.builtin.include_role:
        name: snmpd
        tasks_from: add
      when: "'snmpd' in tasks"
      