---
- name: Deploy Terraform plan
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.homelab.inmem_inv

    - ansible.builtin.include_role:
        name: eingram23.tf_build.terraform
        tasks_from: apply

- name: Create DNS entries in Pihole
  hosts: piholes
  gather_facts: false
  become: true
  become_method: sudo
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml
  
  tasks:

    - ansible.builtin.include_role:
        name: eingram23.pihole.update_localdns
        tasks_from: add
      when: vm_folder_name == "WindowsWG"
