---
- name: Destroy Terraform
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  collections:
    - eingram23.tf_build

  tasks:

    - import_role:
        name: terraform
        tasks_from: destroy

- name: Remove DNS entries from Pihole
  hosts: piholes
  gather_facts: false
  become: true
  become_method: sudo
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml
  
  collections:
    - eingram23.pihole

  tasks:

    - import_role:
        name: pihole_remove
      when: vm_folder_name == "WindowsWG"

- name: Remove computer object from HOMELAB.LOCAL domain
  hosts: HL-DC1.homelab.local
  gather_facts: false
  become: true
  become_method: runas
  ignore_unreachable: true

  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  collections:
    - eingram23.homelab

  tasks:

    - ansible.builtin.include_role:
        name: remove_ad_computer
      vars:
        ad_computer: "{{ vm_name_list_item }}"
      with_items:
        - "{{ vm_name_list }}"
      loop_control:
        loop_var: vm_name_list_item
      when: vm_folder_name == "WindowsHL"
