---
- name: Remove project servers and clean inventory/DNS
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: pull

    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: addchange

    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: push

    - ansible.builtin.include_role:
        name: eingram23.homelab.inmem_inv
      
- name: Run pre destroy tasks on host
  hosts: temp_group
  gather_facts: true
  become: true
  become_method: sudo
  ignore_unreachable: true

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.homelab.rhel_sub
        tasks_from: remove
      when: ansible_facts['distribution'] is defined and ansible_facts['distribution'] == 'RedHat'    

- name: Destroy Terraform
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.tf_build.terraform
        tasks_from: destroy
 
- name: Remove host(s) from DNS
  hosts: piholes
  gather_facts: false
  become: true
  become_method: sudo
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  tasks:
  
    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: remove

- name: Remove target(s) from prometheus server
  hosts: dbsrv1.local.lan
  gather_facts: false
  become: true
  become_user: poduser
  become_method: sudo
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  tasks:
  
    - ansible.builtin.include_role:
        name: eingram23.metrics.prom_target_update
        tasks_from: remove
      when: "'node_exporter' in task"

- name: Remove host(s) from LibreNMS
  hosts: librenms.local.lan
  gather_facts: false
  become: true
  become_user: librenms
  become_method: sudo
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.homelab.snmpd
        tasks_from: remove
      when: "'snmpd' in task"
