---
- name: Destroy Terraform
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml

  collections:
    - eingram23.tf_build

  tasks:

    - import_role:
        name: terraform
        tasks_from: destroy

- name: Remove DNS entries from Pihole
  hosts: piholes
  gather_facts: false
  become: true
  become_method: sudo
  vars_files:
    - ./vars/vars_{{ proj_name }}.yaml
  
  collections:
    - eingram23.pihole

  tasks:

    - import_role:
        name: pihole_remove
      when: vm_folder_name == "WindowsWG"

 