---
collections:
  - community.general
  - containers.podman
  - name: https://github.com/eingram23/ansible-col-homelab.git
    type: git
    version: main
  - name: https://github.com/eingram23/ansible-col-pihole.git
    type: git
    version: main
  - name: https://github.com/eingram23/ansible-col-tf_build.git
    type: git
    version: main
  - name: https://github.com/eingram23/ansible-col-vsphere.git
    type: git
    version: main
  - name: https://github.com/eingram23/ansible-col-splunk.git
    type: git
    version: main
  - name: https://github.com/eingram23/ansible-col-metrics.git
    type: git
    version: main
  - name: https://github.com/eingram23/ansible-col-containers.git
    type: git
    version: main
  