---
# VARS NEEDED: vm_name
- name: get disk info
  hosts: localhost
  gather_facts: true
  become: false

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.vsphere.common
        tasks_from: disk_info