---
- name: Create a snapshot
  hosts: localhost
  become: false
  gather_facts: true

  tasks:
  
    - import_role:
        name: eingram23.vsphere.common_vm_tasks
        tasks_from: vm_create_snap