---
- name: Take snapshot of MCEM config and sql servers prior to updates
  hosts: localhost
  gather_facts: true
  become: false

  vars:
    mcem_vms:
      - HL-SRV1
      - HL-SQL1

  tasks:

    - name: Shutdown MCEM VMs
      ansible.builtin.include_role:
        name: eingram23.vsphere.common
        tasks_from: vm_shutdown_guest
      vars:
        vm_name: "{{ vm_name_item }}"
      loop: "{{ mcem_vms }}"
      loop_control:
        loop_var: vm_name_item

    - name: Snapshot MCEM VMs
      ansible.builtin.include_role:
        name: eingram23.vsphere.common
        tasks_from: vm_create_snap
      vars:
        vm_name: "{{ vm_name_item }}"
      loop: "{{ mcem_vms }}"
      loop_control:
        loop_var: vm_name_item

    - name: Power on HL-SQL1
      ansible.builtin.include_role:
        name: eingram23.vsphere.common
        tasks_from: vm_poweron
      vars:
        vm_name: "HL-SQL1"
    
    - name: Wait 2 minutes before starting HL-SRV1
      ansible.builtin.pause:
        minutes: 2

    - name: Power on HL-SRV1
      ansible.builtin.include_role:
        name: eingram23.vsphere.common
        tasks_from: vm_poweron
      vars:
        vm_name: "HL-SRV1"