apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.10.0.230-10.10.0.250

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-pool-l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-pool