---
# Run with -kK and -e "ansible_user= " to create initial user
- name: Add ansible user
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true
  become_method: sudo
    
  tasks:

    - ansible.builtin.import_role:
        name: eingram23.homelab.add_ansible_user