---
- name: Run site baseline plays
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: true
  become: true
  become_method: sudo

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.homelab.add_eingram_user
      when: "'add_eingram_user' in task"

    - ansible.builtin.include_role: 
        name: eingram23.homelab.add_ansible_user
      when: "'add_ansible_user' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.chrony
      when: "'chrony' in task"

    - ansible.builtin.include_role: 
        name: eingram23.homelab.install_core_pkgs
      when: "'install_core_pkgs' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.container_host
      when: "'container_host' in task"

    - ansible.builtin.include_role:
        name: eingram23.splunk.splunk_uf
      when: "'splunk_uf' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.mount_nas
      when: "'mount_nas' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.snmpd
      when: "'snmpd' in task"

    - ansible.builtin.include_role:
        name: eingram23.metrics.node_exporter
      when: "'node_exporter' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.rhel_sub
        tasks_from: add
      when: "'rhel_sub_add' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.rhel_sub
        tasks_from: remove
      when: "'rhel_sub_del' in task"

    - ansible.builtin.include_role:
        name: eingram23.metrics.windows_exporter
      when: "'windows_exporter' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.filesystem
        tasks_from: zfs
      when: "'zfs' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.filesystem
        tasks_from: nfs
      when: "'nfs' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.filesystem
        tasks_from: samba
      when: "'samba' in task"

