---
- name: Update software/kernel packages
  hosts: "{{ hostvar|default([]) }}"
  become: true
  become_method: sudo

  tasks:

    - name: Update Ubuntu/Debian hosts
      ansible.builtin.include_role:
        name: eingram23.homelab.linux_update
        tasks_from: update_deb_ub
      when: ansible_facts['distribution'] != 'CentOS' and
            ansible_facts['distribution'] != 'RedHat' and
            ansible_facts['distribution'] != 'Rocky' and
            check_reboot == "n"

    - name: Update CentOS hosts
      ansible.builtin.include_role:
        name: eingram23.homelab.linux_update
        tasks_from: update_centos
      when: ansible_facts['distribution'] == 'CentOS' and
            check_reboot == "n"

    - name: Update Rocky/RHEL hosts
      ansible.builtin.include_role:
        name: eingram23.homelab.linux_update
        tasks_from: update_redhat
      when: (ansible_facts['distribution'] == 'RedHat' or
            ansible_facts['distribution'] == 'Rocky') and
            check_reboot == "n"

    - name: Check if reboot required
      ansible.builtin.include_role:
        name: eingram23.homelab.linux_update
        tasks_from: checkreboot
      when: check_reboot == "y"

