---
# TAGS - snmpd, splunk, container_host, webapps, node_exporter
- name: Deploy new server(s) - run roles against piholes
  hosts: piholes
  gather_facts: false
  become: true
  become_method: sudo
  vars_files:
    - ./vars/vars_linux_rocky2.yaml

  collections:
    - eingram23.pihole
  
  tasks:

    - name: Import pihole_add role
      import_role:
        name: pihole_add
      tags: 
        - always

- name: Run localhost roles
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - ./vars/vars_linux_rocky2.yaml

  collections:
    - eingram23.homelab
    - eingram23.tf_build

  tasks:

    - name: Intall dnf python module
      ansible.builtin.shell: pip3 install python3-dnf
      
    - name: Install terraform pre-req
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Install terraform
      ansible.builtin.dnf:
        enablerepo:
          - https://rpm.releases.hashicorp.com/$release/hashicorp.repo
        name: terraform
        state: present
      
    - name: Import inmem_inv role
      import_role:
        name: inmem_inv 
      tags: 
        - always
    - name: Import terraform_apply role
      import_role:
        name: terraform_linux_apply
      tags:
        - always

- name: Run roles against new server(s)
  hosts: temp_group
  become: true
  become_method: sudo

  collections:
    - eingram23.homelab

  roles:
    - role: rhel_sub_add
      when: ansible_facts['distribution'] == 'RedHat'
      tags:
        - always
    - role: add_eingram_user
      tags:
        - always
    - role: chrony
      tags:
        - always
    - role: install_core_pkgs
      tags:
        - always
    - role: container_host
      tags:
        - container_host
        - never
    - role: webapps
      tags:
        - webapps
        - never
    - role: splunk_uf
      tags:
        - splunk_uf
        - never
    - role: snmpd
      tags:
        - snmpd
        - never
    - role: node_exporter
      tags:
        - node_exporter
        - never

- name: Add target to prometheus server
  hosts: grafana.local.lan
  gather_facts: false
  become: true
  become_user: poduser
  become_method: sudo
  vars_files:
    - ./vars/vars_linux_rocky2.yaml

  collections:
    - eingram23.homelab
     
  tasks:
  
    - name: Import prometheus_target_update_nix role
      import_role:
        name: prometheus_target_update_nix
      tags:
        - node_exporter
        - never
