---
- name: Setup Digital Ocean backup (DO side)
  hosts: "yc-appsrv1"
  gather_facts: false
  become: true
  become_method: sudo
  become_user: poduser

  tasks:

    - name: Run do_backup tasks from backups role
      ansible.builtin.include_role:
        name: eingram.homelab.backups
        tasks_from: do_backup

- name: Setup Digital Ocean backup (homenas side)
  hosts: "homenas.local.lan"
  gather_facts: false
  become: true
  become_method: sudo
  become_user: shareaccess

  tasks:

    - name: Check if rsync installed
      ansible.builtin.package:
        name: rsync
        state: present
      become: true
      become_method: sudo
      become_user: root

    - name: Check if ssh keys already exist
      ansible.builtin.stat:
        path: .ssh/id_rsa
      register: ssh_key_exists
        
    - name: Generate ssh keys
      ansible.builtin.shell:
        ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa
      when: not ssh_key_exists

    - name: get contents of id_rsa.pub
      ansible.builtin.slurp:
        src: .ssh/id_rsa.pub
      register: ssh_id_rsa

    - name: Set fact with pub key
      ansible.builtin.set_fact:
        ssh_pub_key: "{{ ssh_id_rsa.content | b64decode }}"

    - name: Set authorized key
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ ssh_pub_key }}"
      delegate_to: yc-appsrv1

    - name: Set up cronjob to copy down backups from DO
      ansible.builtin.cron:
        name: "rsync backups from DO"
        hour: "2"
        job: "rsync -a --delete -e "ssh ansible@138.68.18.20:/home/shared/app_backups/ /mnt/pool0/Shared/Backup/DigitalOcean"