---
- name: Add ansible user
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true
  become_method: sudo

  collections:
    - eingram23.homelab
    
  tasks:

    - ansible.builtin.import_role:
        name: add_ansible_user