# Run with ansible-playbook -kK

---
- name: Run this to allow passwordless ssh and passwordless sudo 
  hosts: "{{ hostvar|default([]) }}"
  gather_facts: no
  remote_user: eingram
  become: yes
  become_method: sudo

  vars_prompt:
    - name: "hosts_prompt"
      prompt: "MAKE SURE TO RUN THIS WITH -kK - Enter host/group to add new ssh keys to"
      private: no
    - name: "pub_key"
      prompt: "Enter ssh pub key"
      private: no
  
  tasks:
  
    - name: Create user .ssh dir
      file:
        path: "/home/eingram/.ssh"
        owner: eingram
        group: eingram
        mode: 0755
        state: directory

    - name: Create authorized_keys if not already existing
      file:
        path: "/home/eingram/.ssh/authorized_keys"
        owner: eingram
        group: eingram
        mode: 0600
        state: touch

    - name: Add public key
      lineinfile:
        path: "/home/eingram/.ssh/authorized_keys"
        line: "{{ pub_key }}"

    - name: Create sudoers.d entry
      file:
        path: "/etc/sudoers.d/eingram"
        owner: root
        group: root
        mode: 0644
        state: touch

    - name: Add sudo entry
      lineinfile:
        path: "/etc/sudoers.d/eingram"
        line: "eingram ALL=(ALL:ALL) NOPASSWD: ALL"
        