---
- name: Install k3s on master node
  hosts: k3s1.local.lan,k3s2.local.lan,k3s3.local.lan
  gather_facts: false
  become: true
  become_method: sudo
  serial: 1

  tasks:

    - name: Disable firewall (RHEL/CentOS)
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: false

    - name: Check if already installed
      ansible.builtin.stat:
        path: /usr/local/bin/k3s
      register: k3s_installed

    - block:
        - name: Run k3s install script
          ansible.builtin.shell: >
            curl -sfL https://get.k3s.io | sh -s - server
            --token=k3s
            --datastore-endpoint="mysql://"
            --write-kubeconfig-mode 644
          when: not k3s_installed.stat.exists

        - name: Install k3s service
          ansible.builtin.systemd:
            name: k3s
            enabled: true
            state: started

        - name: Grab token from master node
          ansible.builtin.shell: 
            cmd: cat /var/lib/rancher/k3s/server/node-token
          register: k3s_master_token

        - name: Set var to token
          ansible.builtin.set_fact:
            token: "{{ k3s_master_token.stdout }}"
      when: inventory_hostname != "k3s3.local.lan"

    - block:
        - name: Run k3s install script
          ansible.builtin.shell: >
            curl -sfL https://get.k3s.io | K3S_URL=https://k3s1.local.lan:6443
            K3S_TOKEN={{ hostvars['k3s1.local.lan']['token'] }} sh -
          when: not k3s_installed.stat.exists

        - name: Install k3s-agent service
          ansible.builtin.systemd:
            name: k3s-agent
            enabled: true
            state: started
      when: inventory_hostname == "k3s3.local.lan"
