---
- name: Open firewall port(s)
  hosts: "{{ hostvar }}"
  become: true
  become_method: sudo
  gather_facts: false

  tasks: 

    - ansible.builtin.include_role:
        eingram23.homelab.firewall
      vars:
        fw_port: fw_port_list