---
- name: Run site baseline plays
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: true
  become: true
  become_method: sudo

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.homelab.add_eingram_user
      when: "'add_eingram_user' in task"

    - ansible.builtin.include_role: 
        name: eingram23.homelab.add_ansible_user
      when: "'add_ansible_user' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.chrony
      when: "'chrony' in task"

    - ansible.builtin.include_role: 
        name: eingram23.homelab.install_core_pkgs
      when: "'install_core_pkgs' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.container_host
      when: "'container_host' in task"

    - ansible.builtin.include_role:
        name: eingram23.splunk.splunk_uf
      when: "'splunk_uf' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.snmpd
      when: "'snmpd' in task"

    - ansible.builtin.include_role:
        name: eingram23.metrics.node_exporter
      when: "'node_exporter' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.webapps
      when: "'webapps' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.rhel_sub
        tasks_from: add
      when: "'rhel_sub_add' in task"

    - ansible.builtin.include_role:
        name: eingram23.homelab.rhel_sub
        tasks_from: remove
      when: "'rhel_sub_del' in task"

    - ansible.builtin.include_role:
        name: eingram23.metrics.windows_exporter
      when: "'windows_exporter' in task"

- name: Add target to prometheus server
  hosts: dbsrv1.local.lan
  gather_facts: false
  become: true
  become_user: poduser
  become_method: sudo

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.metrics.prom_target_update
        tasks_from: add
      vars:
        prom_port: "9100"
      when: "'node_exporter' in task"

- name: Add host to LibreNMS
  hosts: librenms.local.lan
  gather_facts: false
  become: true
  become_user: librenms
  become_method: sudo

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.homelab.snmpd
        tasks_from: add
      when: "'snmpd' is in task"
