---
- name: Run site baseline plays
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: true
  become: true
  become_method: sudo

  collections:
    - eingram23.homelab
    - eingram23.pihole

  tasks:

    - ansible.builtin.include_role:
        name: add_eingram_user
      when: "'add_eingram_user' in tasks"

    - ansible.builtin.include_role: 
        name: add_ansible_user
      when: "'add_ansible_user' in tasks"

    - ansible.builtin.include_role:
        name: chrony
      when: "'chrony' in tasks"

    - ansible.builtin.include_role: 
        name: install_core_pkgs
      when: "'install_core_pkgs' in tasks"

    - ansible.builtin.include_role:
        name: container_host
      when: "'container_host' in tasks"

    - ansible.builtin.include_role:
        name: splunk_uf
      when: "'splunk_uf' in tasks"

    - ansible.builtin.include_role:
        name: snmpd
      when: "'snmpd' in tasks"

    - ansible.builtin.include_role:
        name: node_exporter
      when: "'node_exporter' in tasks"

    - ansible.builtin.include_role:
        name: webapps
      when: "'webapps' in tasks"

    - ansible.builtin.include_role:
        name: rhel_sub_add
      when: "'rhel_sub_add' in tasks"

    - ansible.builtin.include_role:
        name: rhel_sub_del
      when: "'rhel_sub_del' in tasks"

    - ansible.builtin.include_role:
        name: windows_exporter
      when: "'windows_exporter' in tasks"

- name: Add target to prometheus server
  hosts: grafana.local.lan
  gather_facts: false
  become_user: poduser
  become_method: sudo

  collections:
    - eingram23.homelab

  tasks:

    - ansible.builtin.include_role:
        name: prometheus_target_update_nix
      when: "'node_exporter' in tasks"

    - ansible.builtin.include_role:
        name: prometheus_target_update_win
      when: "'windows_exporter' in tasks"
