---
- name: Run site baseline plays
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: true
  become: true
  become_method: sudo

  collections:
    - eingram23.homelab
    - eingram23.pihole

  tasks:

    - ansible.builtin.include_role:
        name: add_eingram_user
      when: task == "add_eingram_user"

    - ansible.builtin.include_role: 
        name: add_ansible_user
      when: task == "add_ansible_user"

    - ansible.builtin.include_role:
        name: chrony
      when: task == "chrony"

    - ansible.builtin.include_role: 
        name: install_core_pkgs
      when: task == "install_core_pkgs"

    - ansible.builtin.include_role:
        name: container_host
      when: task == "container_host"

    - ansible.builtin.include_role:
        name: splunk_uf
      when: task == "splunk_uf"

    - ansible.builtin.include_role:
        name: snmpd
      when: task == "snmpd"

    - ansible.builtin.include_role:
        name: node_exporter
      when: task == "node_exporter"

    - ansible.builtin.include_role:
        name: webapps
      when: task == "webapps"

    - ansible.builtin.include_role:
        name: rhel_sub_add
      when: task == "rhel_sub_add"

    - ansible.builtin.include_role:
        name: rhel_sub_del
      when: task == "rhel_sub_del"

    - ansible.builtin.include_role:
        name: windows_exporter
      when: task == "windows_exporter"

- name: Add target to prometheus server
  hosts: grafana.local.lan
  gather_facts: false
  become_user: poduser
  become_method: sudo

  collections:
    - eingram23.homelab

  tasks:

    - ansible.builtin.include_role:
        name: prometheus_target_update_nix
      when: task == "node_exporter"

    - ansible.builtin.include_role:
        name: prometheus_target_update_win
      when: task == "windows_exporter"
