---
- name: Run site baseline plays
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: true
  become: true
  become_method: runas

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.homelab.snmpd
        tasks_from: win_snmp
      when: "'snmp' in task"

    - ansible.builtin.include_role:
        name: eingram23.metrics.windows_exporter
      when: "'windows_exporter' in task"

- name: Add target to prometheus server
  hosts: grafana.local.lan
  gather_facts: false
  become: true
  become_user: poduser
  become_method: sudo

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.metrics.prom_target_update
        tasks_from: add
      vars:
        prom_port: "9182"
      when: "'windows_exporter' in task"

- name: Add host to LibreNMS
  hosts: librenms.local.lan
  gather_facts: false
  become: true
  become_user: librenms
  become_method: sudo

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.homelab.snmpd
        tasks_from: add
      when: "'snmp' is in task"
