---
- name: Deploy awx to k3s
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  environment:
    K8S_AUTH_KUBECONFIG: "{{ lookup('hashi_vault', 'secret=secret/kubernetes/kubeconfig:k3s') }}"
    
  tasks:

    - name: Deploy awx
      ansible.builtin.include_role:
        name: eingram23.kubernetes.awx
      tags:
        - always
