---
- name: Deploy awx to k3s
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    kubeconfig: "{{ lookup('hashi_vault', 'secret=secret/kubernetes/kubeconfig:k3s' + env | default('')) }}"

  tasks:

    - name: Create .kube folder
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: '0755'
      tags: always

    - name: Create kubeconfig
      ansible.builtin.copy:
        content: "{{ kubeconfig }}"
        dest: ~/.kube/config
        mode: '0400'
      tags: always

    - name: Deploy awx
      ansible.builtin.include_role:
        name: eingram23.kubernetes.awx
      tags: always
