---
# VARS NEEDED: hostvar
- name: Deploy cert-manager to k3s
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.kubernetes.cert_manager
