---
# VARS NEEDED: hostvar
- name: Deploy cert-manager to Tanzu
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.kubernetes.cert_manager_tanzu
