---
# VARS NEEDED: hostvar,deployment
- name: Kubernetes Deployment
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: false

  tasks:

    - name: Copy definition to master node
      ansible.builtin.copy:
        src: ./files/dashboard.yaml
        dest: /opt/kubernetes/defs/{{ deployment }}.yaml
        mode: '0644'

    - name: Deploy from local file
      kubernetes.core.k8s:
        state: absent
        src: /opt/kubernetes/defs/{{ deployment }}.yaml
        kubeconfig: /etc/rancher/k3s/k3s.yaml
