---
- name: Deploy monitoring to k3s
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  tasks:

    - name: Deploy monitoring stack
      ansible.builtin.include_role:
        name: eingram23.kubernetes.monitoring
      tags:
        - always
        - update_prom

    - name: Post config message
      ansible.builtin.debug:
        msg:
        - "Grafana default user/pw - admin/admin"
        - "Add the following dashboards"
        - "   15282 - k3s"
        - "   1860 - node exporter"
        - "   11243 - vmware"
        - "   14694 - windows exporter"
        - "   13032 - longhorn"