---
- name: Deploy gitea to k3s
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  tasks:

    - name: Deploy gitea
      ansible.builtin.include_role:
        name: eingram23.kubernetes.gitea