---
# TAGS
# grafana - Deploy/update grafana
# alertmanager - Deploy/update alerting
# update_promjobs - add/update scrape jobs
# update_grafdash - add/update grafana dashboard config maps
- name: Deploy monitoring to k3s
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  tasks:

    - name: Deploy monitoring stack
      ansible.builtin.include_role:
        name: eingram23.kubernetes.monitoring
      tags:
        - grafana
        - update_grafdash
        - update_promjobs
        - alertmanager


