---
- name: Deploy awx to k3s
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  tasks:

    - name: Deploy awx
      ansible.builtin.include_role:
        name: eingram23.kubernetes.awx
      tags:
        - always
