---
- name: Deploy traefik v2 with IngressRoute CRD
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.kubernetes.traefik_v2