---
- name: Deploy monitoring to k3s
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  tasks:

    - name: Deploy monitoring stack
      ansible.builtin.include_role:
        name: eingram23.kubernetes.monitoring
      tags:
        - always


