---
- name: Deploy duckdns to k3s
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  tasks:

    - name: Deploy duckdns
      ansible.builtin.include_role:
        name: eingram23.kubernetes.duckdns