---
- name: Deploy duckdns to k3s
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  vars:
    kubeconfig: "{{ lookup('hashi_vault', 'secret=secret/kubernetes/' + k8shost + ':kubeconfig' | default('')) }}"

  tasks:

    - name: Create .kube folder
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: '0755'
      tags: always

    - name: Create kubeconfig
      ansible.builtin.copy:
        content: "{{ kubeconfig }}"
        dest: ~/.kube/config
        mode: '0400'
      tags: always

    - name: Deploy duckdns
      ansible.builtin.include_role:
        name: eingram23.kubernetes.duckdns