---
# VARS: cert, env, master_node
- name: Deploy gitea to k3s
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: Set environment
      ansible.builtin.import_role:
        name: eingram23.kubernetes.kubeconfig

    - name: Deploy gitea
      ansible.builtin.import_role:
        name: eingram23.kubernetes.gitea
