---
# VARS: cert, env
- name: Deploy gitea certs to k3s
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: false

  vars:
    kubeconfig: "{{ lookup('hashi_vault', 'secret=secret/kubernetes/kubeconfig:k3s' + env | default('')) }}"

  tasks:

    - name: Create .kube folder
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Create kubeconfig
      ansible.builtin.copy:
        content: "{{ kubeconfig }}"
        dest: ~/.kube/config
        mode: '0400'
      delegate_to: localhost

    - name: Deploy gitea
      ansible.builtin.include_role:
        name: eingram23.kubernetes.gitea
        tasks_from: priv_registry
