---
- name: Deploy grafana agent to k3s
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: Set environment
      ansible.builtin.import_role:
        name: eingram23.kubernetes.kubeconfig

    - name: Run grafana_agent role
      ansible.builtin.import_role:
        name: eingram23.kubernetes.grafana_agent
