- name: Install metallb load balancer for kubernetes
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  tasks:

    - name: Install metallb and create ip pool
      ansible.builtin.include_role:
        name: eingram23.kubernetes.manifest
        tasks_from: apply
      loop:
        - "metallb-native"
        - "metallb-ippool"
      loop_control:
        loop_var: manifest_item
      vars:
        manifest: "{{ manifest_item }}"
