---
### VARS NEEDED: hostprefix, hostvar
- name: Install prereqs
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: true
  become_method: sudo

  tasks:

    - name: Run k3s prereq role
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: prereq
        
- name: Finish setup
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: true
  become_method: sudo

  tasks:

    - name: Run remnodes role
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: remnodes

- name: Re-deploy longhorn
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    kubeconfig: "{{ lookup('hashi_vault', 'secret=secret/kubernetes/kubeconfig:k3s' + env | default('')) }}"

  tasks:

    - name: Create .kube folder
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: '0755'
      tags: always

    - name: Create kubeconfig
      ansible.builtin.copy:
        content: "{{ kubeconfig }}"
        dest: ~/.kube/config
        mode: '0400'
      tags: always

    - name: Deploy longhorn
      ansible.builtin.include_role:
        name: eingram23.kubernetes.longhorn
        tasks_from: addnode
