- name: Post k3s install tasks
# VARS NEEDED: hostvar, ip_range (xxx.xxx.xxx.xxx-xxx.xxx.xxx.xxx), env (-dev)
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  tasks:

    - name: Deploy metallb
      ansible.builtin.import_role:
        name: eingram23.kubernetes.metallb
      tags:
        - metallb

    - name: Deploy cert_manager
      ansible.builtin.import_role:
        name: eingram23.kubernetes.cert_manager
      tags:
        - cert_manager

    - name: Deploy traefik dashboard ingressroute
      ansible.builtin.import_role:
        name: eingram23.kubernetes.traefik_ingress
      tags:
        - traefik

    - name: Deploy kubernetes dashboard
      ansible.builtin.import_role:
        name: eingram23.kubernetes.kubernetes_dashboard
      tags:
        - dashboard

    - name: Deploy longhorn
      ansible.builtin.import_role:
        name: eingram23.kubernetes.longhorn
      tags:
        - longhorn

    - name: Deploy monitoring stack
      ansible.builtin.import_role:
        name: eingram23.kubernetes.monitoring
      tags:
        - monitoring
        
    - name: Deploy vault
      ansible.builtin.import_role:
        name: eingram23.kubernetes.vault
      tags:
        - vault