---
### VARS NEEDED: host_prefix
- name: Install prereqs
  hosts: "{{ host_prefix }}[1-3].local.lan"
  gather_facts: false
  become: true
  become_method: sudo
  ignore_unreachable: true

  tasks:

    - name: Run k3s prereq role
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: prereq

- name: Install k3s on first node
  hosts: "{{ host_prefix }}1.local.lan"
  gather_facts: false
  become: true
  become_method: sudo

  tasks:

    - name: Run firstnode role
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: firstnode

    - name: Wait
      ansible.builtin.pause:
        seconds: 60
        
- name: Finish setup
  hosts: "{{ host_prefix }}[2-3].local.lan"
  gather_facts: false
  become: true
  become_method: sudo
  ignore_unreachable: true

  tasks:

    - name: Run remnodes role
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: remnodes
