- name: Post k3s install tasks
# VARS NEEDED: hostvar, ip_range (xxx.xxx.xxx.xxx-xxx.xxx.xxx.xxx), env (-dev)
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  tasks:

    - name: Deploy metallb
      ansible.builtin.include_role:
        name: eingram23.kubernetes.metallb
      tags:
        - all
        - metallb

    - name: Deploy longhorn
      ansible.builtin.include_role:
        name: eingram23.kubernetes.longhorn
      tags:
        - all
        - longhorn

    - name: Deploy vault
      ansible.builtin.include_role:
        name: eingram23.kubernetes.vault
      tags:
        - all
        - vault

    - name: Deploy cert-manager
      ansible.builtin.include_role:
        name: eingram23.kubernetes.cert-manager
      tags:
        - all
        - cert-manager

    - name: Deploy traefik dashboard ingressroute
      ansible.builtin.include_role:
        name: eingram23.kubernetes.traefik
      tags:
        - all
        - traefik

    - name: Deploy kubernetes dashboard
      ansible.builtin.include_role:
        name: eingram23.kubernetes.kubernetes_dashboard
      tags:
        - all
        - dashboard
