- name: Post k3s install tasks
# VARS NEEDED: ip_range (xxx.xxx.xxx.xxx-xxx.xxx.xxx.xxx), env (-dev)
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    kubeconfig: "{{ lookup('hashi_vault', 'secret=secret/kubernetes/kubeconfig:k3s' + env) }}"

  tasks:

    - name: Deploy metallb
      ansible.builtin.import_role:
        name: eingram23.kubernetes.metallb
      tags:
        - metallb

    - name: Deploy cert_manager
      ansible.builtin.import_role:
        name: eingram23.kubernetes.cert_manager
      tags:
        - cert_manager

    - name: Deploy kubernetes dashboard
      ansible.builtin.import_role:
        name: eingram23.kubernetes.kubernetes_dashboard
      tags:
        - dashboard

    - name: Deploy longhorn
      ansible.builtin.import_role:
        name: eingram23.kubernetes.longhorn
      tags:
        - longhorn

    - name: Deploy vault
      ansible.builtin.import_role:
        name: eingram23.kubernetes.vault
      tags:
        - vault

    - name: Deploy traefik_ingress
      ansible.builtin.import_role:
        name: eingram23.kubernetes.traefik_ingress
      tags:
        - traefik_ingress
