---
- name: Copy kubeconfig from k3s master node to vault
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: true
  become: true

  tasks:

    - name: Import kubeconfig role
      ansible.builtin.import_role:
        name: eingram23.kubernetes.k3s
        tasks_from: create_kubeconfig.yaml
