- name: Migrate pvc
# VARS needed: namespace, source, target
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  tasks:

    - name: Deploy longhorn
      ansible.builtin.include_role:
        name: eingram23.kubernetes.migrate_pvc