- name: Post k3s install tasks
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  tasks:

    - name: Deploy metallb
      ansible.builtin.include_role:
        name: eingram23.kubernetes.metallb

    - name: Deploy traefik dashboard ingressroute
      ansible.builtin.include_role:
        name: eingram23.kubernetes.traefik

    - name: Deploy kubernetes dashboard
      ansible.builtin.include_role:
        name: eingram23.kubernetes.kubernetes-dashboard