---
- name: Deploy splunk to k3s
  hosts: localhost
  gather_facts: false
  become: false

  environment:
    K8S_AUTH_KUBECONFIG: "{{ lookup('hashi_vault', 'secret=secret/kubernetes/kubeconfig:k3s') }}"
    
  tasks:

    - name: Deploy splunk
      ansible.builtin.include_role:
        name: eingram23.kubernetes.splunk
      tags:
        - always