---
- name: Deploy splunk to k3s
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: Set environment
      ansible.builtin.import_role:
        name: eingram23.kubernetes.kubeconfig

    - name: Deploy splunk
      ansible.builtin.include_role:
        name: eingram23.kubernetes.splunk
