---
- name: Setup tanzu cluster with prereqs (contour, certmanager)
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.kubernetes.tanzu
