---
- hosts: k3s-dev1.local.lan
  gather_facts: false
  become: false

  tasks:

    - name: Get svc info
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        name: traefik
        namespace: kube-system
        kubeconfig: /etc/rancher/k3s/k3s.yaml
      register: service

    - ansible.builtin.set_fact:
        ip_address: "{{ service | json_query('resources[0].status.loadBalancer.ingress[0].ip') }}"

    - ansible.builtin.debug: 
        var: ip_address