---
# VARS NEEDED: hostvar, unifi_ip
- name: Deploy unifi controller to k3s
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.kubernetes.unifi_controller