---
- name: Uninstall traefik from kubernetes cluster
  hosts: "{{ host_prefix }}[1-3].local.lan"
  gather_facts: false
  become: false
  
  tasks:

    - block:
        - name: Remove helm resources
          kubernetes.core.helm:
            name: "{{ helm_item }}"
            state: absent
            release_namespace: kube-system
            kubeconfig: /etc/rancher/k3s/k3s.yaml
          loop:
            - traefik
            - traefik-crd
          loop_control:
            loop_var: helm_item

        - name: Remove traefik resources
          ansible.builtin.shell: kubectl -n kube-system delete helmchart traefik traefik-crd
      when: inventory_hostname == host_prefix + "1.local.lan"

    - block:
        - name: Touch traefik.yaml.skip
          ansible.builtin.file:
            path: /var/lib/rancher/k3s/server/manifests/traefik.yaml.skip
            state: touch
            mode: '0400'

        - name: Restart k3s
          ansible.builtin.systemd:
            name: k3s
            state: restarted
      become: true
      become_method: sudo
      when: inventory_hostname != host_prefix + "3.local.lan"

    - name: Restart k3s-agent
      ansible.builtin.systemd:
        name: k3s-agent
        state: restarted
      become: true
      become_method: sudo
      when: inventory_hostname == host_prefix + "3.local.lan"