---
# VARS NEEDED: hostvar, env
# TAGS: unseal, show_token
- name: Deploy vault to k3s
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    kubeconfig: "{{ lookup('hashi_vault', 'secret=secret/kubernetes/' + k8shost + ':kubeconfig' | default('')) }}"

  tasks:

    - name: Create .kube folder
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: '0755'

    - name: Create kubeconfig
      ansible.builtin.copy:
        content: "{{ kubeconfig }}"
        dest: ~/.kube/config
        mode: '0400'

    - ansible.builtin.include_role:
        name: eingram23.kubernetes.vault
      tags:
        - show_token
        - unseal
        - update_vaultconf
