---
- name: Check dotnet 4 version
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true

  tasks:

    - name: Get dotnet 4 version from registry
      ansible.windows.win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\
        name: Release
      register: dot_net_ver

    - name: Display version
      ansible.builtin.debug:
        var: dot_net_ver.value

    - name: 4.8.1 or later
      when: dot_net_ver.value >= 533320
      ansible.builtin.debug:
        msg: ".NET 4 version is 4.8.1 or later"

    - name: 4.8
      when: dot_net_ver.value >= 528040 and dot_net_ver.value < 533320
      ansible.builtin.debug:
        msg: ".NET 4 version is 4.8"

    - name: 4.7.2
      when: dot_net_ver.value >= 461808 and dot_net_ver.value < 528040
      ansible.builtin.debug:
        msg: ".NET 4 version is 4.7.2"

    - name: 4.7.1
      when: dot_net_ver.value >= 461308 and dot_net_ver.value < 461808
      ansible.builtin.debug:
        msg: ".NET 4 version is 4.7.1"

    - name: 4.7
      when: dot_net_ver.value >= 460798 and dot_net_ver.value < 461308
      ansible.builtin.debug:
        msg: ".NET 4 version is 4.7"

    - name: 4.6.2
      when: dot_net_ver.value >= 394802 and dot_net_ver.value < 460798
      ansible.builtin.debug:
        msg: ".NET 4 version is 4.6.2"

    - name: 4.6.1
      when: dot_net_ver.value >= 394254 and dot_net_ver.value < 394802
      ansible.builtin.debug:
        msg: ".NET 4 version is 4.6.1"

    - name: 4.6
      when: dot_net_ver.value >= 393295 and dot_net_ver.value < 394254
      ansible.builtin.debug:
        msg: ".NET 4 version is 4.6"

    - name: 4.5.2
      when: dot_net_ver.value >= 379893 and dot_net_ver.value < 393295
      ansible.builtin.debug:
        msg: ".NET 4 version is 4.5.2"

    - name: 4.5.1
      when: dot_net_ver.value >= 378675 and dot_net_ver.value < 379893
      ansible.builtin.debug:
        msg: ".NET 4 version is 4.5.1"

    - name: 4.5
      when: dot_net_ver.value >= 378389 and dot_net_ver.value < 378675
      ansible.builtin.debug:
        msg: ".NET 4 version is 4.5"
