- name: Chocolatey Tasks
  hosts: "{{ hostvar | default([]) }}"
  become: false
  gather_facts: false

  vars:
    reboot: "no"
    force_install: "no"

  tasks:

    - name: Wake PC if in sleep mode
      ansible.builtin.include_role:
        name: eingram23.homelab.wol

    - name: Ensure Chocolatey itself is installed, using community repo for the bootstrap
      chocolatey.chocolatey.win_chocolatey:
        name: chocolatey

    - name: Install/Upgrade Choco Package(s)
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item }}"
        state: latest
      when: action == "install" and force_install == "no"
      loop: "{{ package }}"

    - name: Install/Upgrade Choco Package(s) (FORCE)
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item }}"
        state: latest
        force: true
      when: action == "install" and force_install == "yes"
      loop: "{{ package }}"

    - name: Remove Choco Package(s)
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item }}"
        state: absent
      when: action == "uninstall"
      loop: "{{ package }}"

    - name: Gather facts from chocolatey
      chocolatey.chocolatey.win_chocolatey_facts:

    - name: Displays the Outdated packages
      ansible.builtin.debug:
        msg: "{{ item.package }}"
      loop: "{{ ansible_chocolatey.outdated }}"

    - name: Install/Upgrade all outdated Choco Package
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item.package }}"
        state: latest
      loop: "{{ ansible_chocolatey.outdated }}"
      when: action == "upgrade_all" and force_install == "no"

    - name: Install/Upgrade all outdated Choco Package (FORCE)
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item.package }}"
        state: latest
        force: true
      loop: "{{ ansible_chocolatey.outdated }}"
      when: action == "upgrade_all" and force_install == "yes"

    - name: Displays the Packages
      ansible.builtin.debug:
        var: ansible_chocolatey.packages

    - name: Reboot host
      ansible.windows.win_reboot:
      when: reboot == "yes"