---
- name: Install Grafana Agent
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true

  tasks:

    - name: Run win_grafana_agent role
      ansible.builtin.import_role:
        name: collections.eingram23.homelab.win_grafana_agent