- name: Chocolatey test
  hosts: "{{ hostvar | default([]) }}"
  become: false
  gather_facts: false

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.homelab.wol

    - name: Install/Upgrade VNC Connect
      chocolatey.chocolatey.win_chocolatey:
        name: vnc-connect
        version: '6.11.0'
        state: present