- name: Chocolatey test
  hosts: "{{ hostvar | default([]) }}"
  become: false
  gather_facts: false

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.homelab.wol

    - name: Install/Upgrade Choco Package
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ package }}"
        state: latest