- name: Run script on host
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: true
  become_user: SYSTEM
  become_method: runas

  vars:
    schtask: disabled

  tasks:

    - name: Create script on host
      ansible.windows.win_copy:
        content: "{{ script }}"
        dest: c:\temp\tempscript.{{ extension }}

    - name: Run win_scripts role
      ansible.builtin.include_role:
        name: eingram23.homelab.win_scripts
      vars:
        script: tempscript.{{ extension }}

    - ansible.builtin.fail:
      when: schtask == "disabled" and ((ps1_output.stderr is defined and ps1_output.stderr != "") or
            (vbs_output.stderr is defined and vbs_output.stderr != "") or
            (bat_output.stderr is defined and bat_output.stderr != ""))