- name: Run script on host
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: true
  become_user: SYSTEM
  become_method: runas

  vars:
    schtask: disabled

  tasks:

    - name: Create script on host
      ansible.windows.win_copy:
        content: "{{ script }}"
        dest: c:\temp\tempscript.{{ extension }}

    - name: Run script via win_shell
      ansible.builtin.include_role:
        name: win_shell
      vars:
        script: tempscript.{{ extension }}
      when: schtask == "disabled"

    - name: Run script via scheduled task
      ansible.builtin.include_role:
        name: win_schtasks
      vars:
        script: tempscript.{{ extension }}
      when: schtask == "enabled"

    - name: Clean up script
      ansible.windows.win_file:
        path: c:\temp\{{ script }}.{{ extension }}
        state: absent      

    - ansible.builtin.fail:
      when: schtask == "disabled" and ((ps1_output.stderr is defined and ps1_output.stderr != "") or
            (vbs_output.stderr is defined and vbs_output.stderr != "") or
            (bat_output.stderr is defined and bat_output.stderr != ""))