---
- name: Run site baseline plays
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: true
  become: true
  become_method: runas

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.homelab.snmpd
        tasks_from: win_snmp
      when: "'snmp' in task"

    - ansible.builtin.include_role:
        name: eingram23.metrics.windows_exporter
      when: "'windows_exporter' in task"

