- name: Run script on host
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: true
  become_method: runas

  tasks:

    - name: Create script to host
      ansible.windows.win_copy:
        content: "{{ script }}"
        dest: c:\temp\script.ps1

    - name: Run script on host
      ansible.windows.win_shell: c:\temp\script.ps1 {{ param }}
      register: output

    - name: Script output 
      ansible.builtin.debug:
        var: output.stdout_lines
        
    - name: Script error
      ansible.builtin.debug:
        var: output.stderr


    - name: Clean up script
      ansible.windows.win_file:
        path: c:\temp\script.ps1
        state: absent