---
- name: Windows updates
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: true
  become: true

  tasks:

    - ansible.builtin.import_role:
        name: eingram23.homelab.wol
      tags: install

    - name: "Run Update Session Orchestrator check to clear GUI cached results"
      win_shell: |
        UsoClient RefreshSettings
        UsoClient ScanInstallWait

    - name: Search-only, return list of found updates (if any)
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Definition Updates
          - Microsoft Defender Antivirus
        state: searched
      register: update_list

    - name: Install updates and reboot
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Definition Updates
          - Microsoft Defender Antivirus
        state: installed
        reboot: true
        reboot_timeout: 1200
      register: update_list
      tags:
        - install
        - never

    - name: Show results
      ansible.builtin.debug:
        var: update_list
      tags: install
    
    - name: Write update data to postgres
      community.postgresql.postgresql_query:
        db: homelab_cmdb
        query: INSERT INTO servers (server_name, os, hardware_type) VALUES ( {{ ansible_inventory_hostname }}, {{ ansible_distribution }} {{ ansible_distribution_version }}, {{ ansible_bios_vendor }} }})
      tags: update_db