---
- name: Add DNS record to Google Cloud DNS
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.gcp.cloud_dns
        tasks_from: add
      vars:
        hostname: test
        record_type: A
        target: 10.10.0.61