---
# VARS NEEDED - hostvar
- name: Create postgres pod and containers (postgres, pgadmin)
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true
  become_method: sudo

  vars:
    fw_port:
      - "5432/tcp"
      - "8081/tcp"
    postgres_container: "postgres"
    pgadmin_container: "pgadmin"
    pod_name: "postgres_pod"
    publish_ports:
      - "5432:5432"
      - "8081:8081"

  tasks:

    - name: Open firewall port for postgres/phpmyadmin
      ansible.builtin.include_role:
        name: eingram23.homelab.firewall

    - block:
        - name: Create pod
          ansible.builtin.include_role:
            name: eingram23.containers.create_pod

        - name: Create postgres container
          ansible.builtin.include_role:
            name: eingram23.containers.postgres

        - name: Create pgadmin container
          ansible.builtin.include_role:
            name: eingram23.containers.pgadmin
      become: true
      become_user: poduser
      become_method: sudo

    - name: Install software req
      ansible.builtin.dnf:
        name: "{{ package_item }}"
        state: present
        disable_gpg_check: true
      loop:
        - 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
        - python3-psycopg2
      loop_control:
        loop_var: package_item

    - name: Disable default postgresql repo
      command: dnf -qy module disable postgresql

    - name: Install postgresql14
      ansible.builtin.dnf:
        name: postgresql14
        state: present

