---
- name: Create mariadb container
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true
  become_method: sudo

  tasks:

    - name: Open firewall port for mariadb 
      ansible.builtin.include_role:
        name: eingram23.homelab.firewall
      vars:
        - fw_port: "{{ mariadb_port.split('\n') | product(['/tcp']) | map('join') | list }}"

    - block:
        - name: Create container
          ansible.builtin.include_role:
            name: eingram23.containers.mariadb
          vars:
            - mysql_port: "{{ mariadb_port.split('\n') | first }}"
      become: true
      become_user: poduser
      become_method: sudo

