---
- name: Create mariadb container
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true
  become_user: poduser
  become_method: sudo

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.containers.mariadb

