---
# VARS NEEDED - hostvar, db_root_pw
- name: Create mariadb pod and containers (mariadb, phpmyadmin)
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true
  become_method: sudo

  vars:
    # - fw_port: "{{ mariadb_port.split('\n') | product(['/tcp']) | map('join') | list }}"
    fw_port:
      - "3306/tcp"
      - "8080/tcp"
    pod_name: "mariadb_pod"
    publish_ports:
      - "3306:3306"
      - "8080:80"

  tasks:

    - name: Open firewall port for mariadb/phpmyadmin
      ansible.builtin.include_role:
        name: eingram23.homelab.firewall

    - block:
        - name: Create pod
          ansible.builtin.include_role:
            name: eingram23.containers.create_pod

        - name: Create mariadb container
          ansible.builtin.include_role:
            name: eingram23.containers.mariadb

        - name: Create phpmyadmin container
          ansible.builtin.include_role:
            name: eingram23.containers.phpmyadmin
      become: true
      become_user: poduser
      become_method: sudo

    - name: Install software req
      ansible.builtin.package:
        name: "{{ package_item }}"
        state: present
      loop:
        - python3-mysql
        - mysql
      loop_control:
        loop_var: package_item

    - name: Create mariadb superuser
      community.mysql.mysql_user:
        login_host: 127.0.0.1
        login_user: root
        login_password: "{{ lookup('hashi_vault', 'secret=secret/data/ssh/eingram:ssh_password') }}"
        state: present
        name: eingram@127.0.0.1
        password: "{{ lookup('hashi_vault', 'secret=secret/data/ssh/eingram:ssh_password') }}"
        priv: '*.*:ALL,GRANT'

    - name: Remove mariadb superuser
      community.mysql.mysql_user:
        login_host: 127.0.0.1
        login_user: root
        login_password: "{{ lookup('hashi_vault', 'secret=secret/data/ssh/eingram:ssh_password') }}"
        state: absent
        name: eingram
        password: "{{ lookup('hashi_vault', 'secret=secret/data/ssh/eingram:ssh_password') }}"
        priv: '*.*:ALL,GRANT'