- name: Deploy nut-upsd pihole
  hosts: "{{ hostvar | default('dietpi1.local.lan') }}"
  gather_facts: false
  become: true
  become_method: sudo

  tasks:

    - name: Install python modules
      ansible.builtin.pip:
        name: "{{ item }}"
      loop:
        - requests
        - docker

    - name: Install prereq packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - openssh-client
        - git

    - ansible.builtin.include_role:
        name: eingram23.containers.nut_upsd_docker
        tasks_from: build
      tags: 
        - build
        - never

    - ansible.builtin.include_role:
        name: eingram23.containers.nut_upsd_docker
      tags: always
