---
- name: Deploy docker pihole
  hosts: piholes
  gather_facts: false
  become: true
  become_method: sudo
  serial: 1

  tasks:

    - name: Install python modules
      ansible.builtin.pip:
        name: "{{ item }}"
      loop:
        - requests
        - docker
    
    - name: Install openssh-client for scp access
      ansible.builtin.apt:
        name: openssh-client
        state: present

    - ansible.builtin.include_role:
        name: eingram23.containers.pihole_docker