---
# NEEDED VARS: hostvar, env
- name: Deploy diversionforum.net
  hosts: "{{ hostvar | default([]) }}"
  become: true
  become_method: sudo
  become_user: poduser
  gather_facts: false

  vars:
  # env: "test" or "www"

  tasks:

    - name: Set facts (www)
      when: env == "www"
      block:
        - ansible.builtin.set_fact:
            nginx_port: 8081

        - ansible.builtin.set_fact:
            phpmyadmin_port: 8084

    - name: Set facts (test)
      when: env == "test"
      block:
        - ansible.builtin.set_fact:
            nginx_port: 8082

        - ansible.builtin.set_fact:
            phpmyadmin_port: 8085

    - name: Deploy diversionforum.net site
      ansible.builtin.include_role:
        name: eingram23.containers.diversionforum

