---
# NEEDED VARS: hostvar, env
- name: Deploy diversionforum.net
  hosts: "{{ hostvar | default([]) }}"
  become: true
  become_method: sudo
  become_user: poduser
  gather_facts: false

  vars:
  # env: "test" or "www"

  tasks:

    - name: Deploy diversionforum.net site
      ansible.builtin.include_role:
        name: eingram23.containers.diversionforum
