---
- name: Deploy plex media server container
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true

  vars:
    fw_port:
      - "32400/tcp"

  tasks:

    - name: Open firewall port
      ansible.builtin.include_role:
        name: eingram23.homelab.firewall

- name: Start plex_srv container
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true
  become_method: sudo
  become_user: poduser

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.containers.plex_srv
