---
- name: Deploy influxdb container
  hosts: "{{ hostvar | default('homenas.local.lan') }}"
  gather_facts: false
  become: true
  become_method: sudo
  become_user: poduser

  tasks:

    - name: Run influxdb container role
      ansible.builtin.import_role:
        name: eingram23.containers.influxdb
