---
# NEEDED VARS: hostvar, ttl, vault_role (local-dot-lan ycdisp-dot-net)
- name: Check cert already exists
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: false

  tasks:

    - ansible.builtin.import_role:
        name: eingram23.containers.node_exporter
        tasks_from: check_cert
      tags:
        - secure
        - never

- name: Deploy node-exporter
  hosts: "{{ hostvar | default([]) }}"
  become: true
  become_method: sudo
  become_user: poduser
  gather_facts: false
  tags: always

  tasks:

    - name: Deploy node-exporter
      ansible.builtin.include_role:
        name: eingram23.containers.node_exporter
