- name: Deploy nut-upsd pihole
  hosts: "{{ hostvar | default('dietpi1.local.lan') }}"
  gather_facts: false
  become: true
  become_method: sudo

  tasks:

    - name: Install python modules
      ansible.builtin.pip:
        name: "{{ item }}"
      loop:
        - requests
        - docker
      tags: always

    - name: Install prereq packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - openssh-client
        - git
      tags: always

    - name: Run nut_pwsh_upsd_docker role/build tasks
      ansible.builtin.import_role:
        name: eingram23.containers.nut_pwsh_upsd_docker
        tasks_from: build
      tags: 
        - build

    - name: Run nut_pwsh_upsd_docker role
      ansible.builtin.include_role:
        name: eingram23.containers.nut_pwsh_upsd_docker
        apply:
          tags: 
            - always
            - build
      tags:
        - always
        - build

    - name: Update shutdown script
      ansible.builtin.import_role:
        name: eingram23.containers.nut_pwsh_upsd_docker
        tasks_from: update_script
      tags: 
        - update_script