---
- name: Deploy prometheus container
  hosts: "{{ hostvar | default([]) }}"
  gather_facts: false
  become: true
  become_method: sudo

  tasks:

    - name: Open firewall ports
      ansible.builtin.include_role:
        name: eingram23.homelab.firewall
      vars:
        fw_port:
          - "9091/tcp"

    - name: Create prometheus folder
      ansible.builtin.file:
        path: /opt/prometheus
        state: directory
        mode: '0755'
        owner: poduser
        group: poduser

    - block:
        - name: Create app pod
          ansible.builtin.include_role:
            name: eingram23.containers.create_pod
          vars:
            pod_name: "prometheus_pod"
            publish_ports:
              - "9091:9090"
              
        - name: Create container
          ansible.builtin.include_role:
            name: eingram23.containers.prometheus
      become: true
      become_user: poduser
      become_method: sudo
