---
# NEEDED VARS: hostvar
- name: Deploy promtail
  hosts: "{{ hostvar | default([]) }}"
  become: true
  become_method: sudo
  become_user: poduser
  gather_facts: false

  tasks:

    - name: Deploy promtail container
      ansible.builtin.import_role:
        name: eingram23.containers.promtail
