---
- hosts: yc-appsrv1-dev.local.lan
  become: true
  become_method: sudo
  become_user: eingram
  gather_facts: false

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.containers.create_pod
      vars:
        pod_name: "ansible"
        publish_ports: "8092:80"
      