---
- name: Backup awx postgresql database
  hosts: "{{ hostvar | default('k3s1.local.lan') }}"
  gather_facts: true
  become: false

  tasks:

    - name: Use kubectl to dump pg awx database
      ansible.builtin.shell: |
        kubectl exec pod/awx-postgres-13-0 -n awx -- pg_dump -U awx > backup.sql

    - name: Fetch backup.sql
      ansible.builtin.fetch:
        src: backup.sql
        dest: /tmp/
        flat: true

    - name: Copy backup.sql to homenas
      ansible.builtin.copy:
        src: /tmp/backup.sql
        dest: /mnt/pool0/Shared/Backup/AWX/backup-{{ ansible_date_time.date }}.sql
        mode: '0644'
      delegate_to: homenas.local.lan

    - name: Remove backup.sql from k3s host
      ansible.builtin.file:
        path: backup.sql
        state: absent
