---
- name: Backup awx postgresql database
  hosts: localhost
  gather_facts: true
  become: false

  vars:
    kubeconfig: "{{ lookup('hashi_vault', 'secret=secret/kubernetes/' + k8shost + ':kubeconfig') }}"

  tasks:

    - name: Create .kube folder
      ansible.builtin.file:
        path: ~/.kube
        state: directory
        mode: '0755'

    - name: Create kubeconfig
      ansible.builtin.copy:
        content: "{{ kubeconfig }}"
        dest: ~/.kube/config
        mode: '0400'

    - name: Use kubectl to dump pg awx database
      ansible.builtin.shell: |
        kubectl exec pod/awx-postgres-13-0 -n awx -- pg_dump -U awx > /var/tmp/backup.sql

    - name: Copy backup.sql to homenas
      ansible.builtin.copy:
        src: /var/tmp/backup.sql
        dest: /mnt/pool0/Shared/Backup/AWX/backup-{{ ansible_date_time.date }}.sql
        mode: '0644'
      delegate_to: homenas.local.lan

    - name: Remove backup.sql
      ansible.builtin.file:
        path: /var/tmp/backup.sql
        state: absent
