---
- name: Export config from awxr
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: Run export tasks
      awx.awx.export:
        controller_host: awx.local.lan
        controller_username: eingram
        controller_password: "{{ lookup('hashi_vault', 'secret=secret/ssh/eingram:ssh_password') }}"
        job_templates: 'TEST - Inmem'
        validate_certs: false
      register: awx_export

    - ansible.builtin.debug:
        var: awx_export