---
proj_root: "/var/tmp/terraform/projects/"

### MAKE EDITS BELOW ###

# Edit this to change distro
vsphere_template: TMP-Rocky9_Packer

vm_folder_name: Linux

vm_ram: 4096
vm_cpu: 2

# All lists must have same # of elements

vsphere_datastore_list:
  - XN_iSCSI_SSD1
  - XN_iSCSI_SSD2
  - XN_iSCSI_SSD2
vsphere_network_list:
  - Lab-LAN1
  - Lab-LAN1
  - Lab-LAN1
vm_name_list:
  - k3s-dev1
  - k3s-dev2
  - k3s-dev3
ip_address_list:
  - 10.10.0.51
  - 10.10.0.52
  - 10.10.0.53
ip_gateway_list:
  - 10.10.0.1
  - 10.10.0.1
  - 10.10.0.1
dns_suffix_list:
  - local.lan
  - local.lan
  - local.lan

# For any extra vmdks (For Windows, start with ID 2)
vm_disks_list: 'vm_disks_list = [{ label = "longhorn1", id = 1, size = 60, thin_provisioned = true }]'

# Uncomment post build tasks to run
task:
  # - none
  - mount_nas
  # - container_host
  # - webapps
  # - splunk_uf
  # - snmpd
  # - node_exporter