---
# VARS NEEDED: customhost
- name: Pull custom.list from git and update
  hosts: localhost
  become: false
  gather_facts: false

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: pull

    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: remove

- name: Remove local DNS record from Piholes
  hosts: "{{ hostvar | default('piholes') }}"
  become: true
  become_method: sudo
  gather_facts: false

  tasks:
    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: update

- name: Push updated custom.list to git
  hosts: localhost
  become: false
  gather_facts: false

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: push

    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: cleanup
  
