---
# VARS NEEDED: customhost, customip
- name: Add/Update local DNS record to Piholes
  hosts: piholes
  become: true
  become_method: sudo
  gather_facts: false
  ignore_unreachable: true

  tasks:
    - ansible.builtin.include_role:
        name: eingram23.pihole.update_localdns
        tasks_from: update.yaml
