---
# VARS NEEDED: customip customhost
- name: Add/Update local DNS record to Piholes
  hosts: "{{ hostvar | default('piholes') }}"
  become: true
  become_method: sudo
  gather_facts: false

  tasks:
    - ansible.builtin.include_role:
        name: eingram23.pihole.update_localdns
        tasks_from: update.yaml
