---
# VARS NEEDED: customip customhost
- name: Pull custom.list from git and update
  hosts: localhost
  become: false
  gather_facts: false

  tasks:

    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: pull

    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: addchange
      when: customhost is defined

- name: Add/Update local DNS record to Piholes
  hosts: "{{ hostvar | default('piholes') }}"
  become: true
  become_method: sudo
  gather_facts: false

  tasks:
    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: update

    - name: Pause 20 seconds for pihole update
      ansible.builtin.pause:
        seconds: 20

- name: Push updated custom.list to git
  hosts: localhost
  become: false
  gather_facts: false

  tasks:

    # - ansible.builtin.pause:
    #     prompt: pause

    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: push
      when: customhost is defined

    - ansible.builtin.include_role:
        name: eingram23.pihole.localdns
        tasks_from: cleanup