---
- name: Create a snapshot of pihole.local.lan
  hosts: localhost
  become: false
  gather_facts: true

  tasks:
  
    - name: Create snapshot
      import_role:
        name: eingram23.vsphere.common_vm_tasks
        tasks_from: vm_create_snap.yml
      vars:
        vm_name: pihole
      when: up_host == "pihole"

- name: Update pihole to latest version
  hosts: pihole.local.lan
  gather_facts: no
  become: yes
  become_method: sudo

  tasks:

    - name: Run pihole_up role on pihole.local.lan
      import_role:
        name: eingram23.pihole.pihole_up
      when: up_host == "pihole"

- name: Update pihole2 to latest version
  hosts: pihole2.local.lan
  gather_facts: no
  become: yes
  become_method: sudo

  tasks:

    - name: Run pihole_up role on pihole2.local.lan
      import_role:
        name: eingram23.pihole.pihole_up
      when: up_host == "pihole2"