---
- name: Update piholes to latest version
  hosts: piholes
  gather_facts: no
  remote_user: ansible 
  become: yes
  become_method: sudo

  tasks:

  - name: Run pihole up 
    command: pihole -up
